### ISSUE TITLE
Objekte mit gleicher Bezeichnung

### ISSUE THREAD

**Issue by dp20eic** [iobroker-community-adapters/ioBroker.wolf-smartset#1]
ich habe mir die Version 0.2.1 des Addapters installiert, soweit ist das auch alles i.O. Ich habe da nur bei den Objekten ein Problem, da mir unter "wolf-smartset.0.Warmwasser.039_NULL" unter den IDs "wolf-smartset.0.Warmwasser.039_NULL.35000900000" und "wolf-smartset.0.Warmwasser.039_NULL.35001400000" der gleiche Name "Warmwassersolltemperatur eingestellt" angezeigt/angegeben ist, auch die Werte mit 50°C sind identisch, siehe Bild:

![image](https://user-images.githubusercontent.com/71387331/111634177-8d76a680-87f6-11eb-80fb-9467a85f30ad.png)

Wenn ich in der Android APP die Wassertemperatur ändere, dann wird der untere Wert auch angepasst genauso der obere zieht dann auch nach, das geschieht in beide Richtungen.

Noch eine Frage, hat nichts mit dem Problem zu tun, was bedeutet "CIRCULARSLIDER"?

VG
Bernd

**Comment by MeisterTR** [comment]
Die Objektstruktur und Objekte selber werden komplett aus den api daten erzeugt. daher sind einige doppelt. wieso dass so ist, kann ich dir nciht sagen... wofür CIRCULARSLIDER genutzt wird kann ich auch nicht sagen. schätze ein helper datenpunkt für den Temeraturslider in der app...
