### ISSUE TITLE
 value "61440" greater than max "1"

### ISSUE THREAD

**Issue by Anzic23** [iobroker-community-adapters/ioBroker.wolf-smartset#102]
**Describe the bug**  
I get comments in the log that the values don't match the specified parameters. The adapter is not connected to the device.

**To Reproduce**  

**Expected behavior**  
correctly loading parameters from the smartset.

**Screenshots & Logfiles**  
![image](https://user-images.githubusercontent.com/37106885/145682859-67113a0d-6311-4698-94f1-eb2b8b864675.png)
![image](https://user-images.githubusercontent.com/37106885/145682955-eb4a33dc-6930-44d9-82aa-1a91c952aeb7.png)

**Versions:**  
 - Adapter version: 1.0.0
 - JS-Controller version: 3.3.18
 - Node version: <node-version> v12.22.6
 - Operating system: raspberry os (debian)

**Comment by Apollon77** [comment]
duplicate #65
