### ISSUE TITLE
iobroker terminiert wolf-smartset instanz - Fehlermeldung

### ISSUE THREAD

**Issue by MCepheus** [iobroker-community-adapters/ioBroker.wolf-smartset#105]
Hallo und vielen Dank erst einmal für die Arbeit, die du in den Adapter gesteckt hast.
Leider bricht mein ioBroker nach einiger Zeit die Wolf-smartset instanz mit Fehlermeldung ab.

Das Ganze sieht im log dann immer so aus:

`<html><body>

wolf-smartset.0 | 2021-12-15 21:55:55.333 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
wolf-smartset.0 | 2021-12-15 21:55:55.331 | info | terminating
wolf-smartset.0 | 2021-12-15 21:55:55.317 | error | Cannot read property 'token_type' of undefined
wolf-smartset.0 | 2021-12-15 21:55:55.316 | error | TypeError:  Cannot read property 'token_type' of undefined    at  WolfSmartSet._createSession  (/opt/iobroker/node_modules/iobroker.wolf-smartset/lib/wss.js:249:11)     at WolfSmartSet.init  (/opt/iobroker/node_modules/iobroker.wolf-smartset/lib/wss.js:38:25)     at processTicksAndRejections (internal/process/task_queues.js:97:5)     at WolfSmartset.main  (/opt/iobroker/node_modules/iobroker.wolf-smartset/main.js:62:3)
wolf-smartset.0 | 2021-12-15 21:55:55.311 | error | unhandled promise rejection: Cannot read property 'token_type' of undefined
wolf-smartset.0 | 2021-12-15 21:55:55.310 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
wolf-smartset.0 | 2021-12-15 21:55:55.308 | error | API GET AUTH TOKEN ERROR: Error: Request failed with status code 429
wolf-smartset.0 | 2021-12-15 21:55:55.119 | info | starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.wolf-smartset, node: v12.22.7, js-controller: 3.3.21
host.raspberrypi | 2021-12-15 21:55:53.065 | info | instance system.adapter.wolf-smartset.0 started with pid 11379
host.raspberrypi | 2021-12-15 21:55:22.986 | info | Restart adapter system.adapter.wolf-smartset.0 because enabled
host.raspberrypi | 2021-12-15 21:55:22.986 | error | instance system.adapter.wolf-smartset.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.raspberrypi | 2021-12-15 21:55:22.986 | error | Caught by controller[1]:     at WolfSmartset.main (/opt/iobroker/node_modules/iobroker.wolf-smartset/main.js:62:3)
host.raspberrypi | 2021-12-15 21:55:22.985 | error | Caught by controller[1]:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
host.raspberrypi | 2021-12-15 21:55:22.985 | error | Caught by controller[1]:     at WolfSmartSet.init (/opt/iobroker/node_modules/iobroker.wolf-smartset/lib/wss.js:38:25)
host.raspberrypi | 2021-12-15 21:55:22.985 | error | Caught  by controller[1]:     at WolfSmartSet._createSession  (/opt/iobroker/node_modules/iobroker.wolf-smartset/lib/wss.js:249:11)
host.raspberrypi | 2021-12-15 21:55:22.984 | error | Caught by controller[1]: TypeError: Cannot read property 'token_type' of undefined
host.raspberrypi | 2021-12-15 21:55:22.984 | error | Caught  by controller[0]: This error originated either by throwing inside of an  async function without a catch block, or by rejecting a promise which  was not handled with .catch(). The promise rejected with the reason:

</body>
</html>`

Das wiederholt sich ständig bis der ioBroker den Adapter komplett abschießt.
Vielleicht liegt das daran, dass bei mir die Beta des iobrokers läuft.
Daher erste einmal nur als Hinweis.

**Versions:**  
 - Adapter version: v1.0.0
 - JS-Controller version: v3.3.21
 - Node version: v12.22.7
 - Operating system: <os-name>

**Comment by Apollon77** [comment]
Please try GitHub version
