### ISSUE TITLE
Wrong min parameter

### ISSUE THREAD

**Issue by CarminKern** [iobroker-community-adapters/ioBroker.wolf-smartset#125]
Hi, "Hysterese Heizkurve" 6001600000 has the wrong min parameter.

![image](https://user-images.githubusercontent.com/38145343/149616146-bbce993a-436d-4af8-87fd-845f6bb7a44c.png)

the correct parameter is 0.5

![image](https://user-images.githubusercontent.com/38145343/149616204-232a6b9f-0099-4a42-8bed-6c5d8cfd0e2f.png)

**Comment by Apollon77** [comment]
duplicate #65
