### ISSUE TITLE
API GET GUI DESK. ERROR: Error: Request failed with status code 400

### ISSUE THREAD

**Issue by e-i-k-e** [iobroker-community-adapters/ioBroker.wolf-smartset#126]
Hallo,

erhalte seit einigen Tagen folgendes im log.

`<html>
<body>

wolf-smartset.0 | 2022-01-16 12:39:09.356 | error | (71285) API GET GUI DESK. ERROR: Error: Request failed with status code 400
-- | -- | -- | --
wolf-smartset.0 | 2022-01-16 12:36:47.557 | error | (71285) API GET GUI DESK. ERROR: Error: Request failed with status code 400
wolf-smartset.0 | 2022-01-16 12:36:46.379 | info | (71285) starting. Version 1.0.0 in /opt/iobroker/node_modules/iobroker.wolf-smartset, node: v14.18.2, js-controller: 3.3.22

</body>
</html>`

Der Adapter steht somit dauerhaft auf gelb.
An der Heizung hat sich nichts geändert und ich komme über die App/Browser auch weiterhin auf die Anlage.

**Comment by e-i-k-e** [comment]
Der Adapter funktioniert plötzlich wieder.

**Comment by e-i-k-e** [comment]
Kommando zurück.

**Comment by Apollon77** [comment]
debug log please

**Comment by Apollon77** [comment]
duplicate #48
