### ISSUE TITLE
Wrong types after "js.controler" update

### ISSUE THREAD

**Issue by dp20eic** [iobroker-community-adapters/ioBroker.wolf-smartset#2]
**Fehlerbeschreibung**  
Ich habe meine ioBroker Installation auf den aktuellen beta Stand gebracht. Bei mir läuft sowihl der "admin 5.0.11" als auch der js.controler 3.3.1.
Seit dem update des js.controlers heute Morgen, bekomme ich Warnungen, das falsche Typen kommen.

`

wolf-smartset.0 | Zeit | debug | Meldung
-- | -- | -- | --
wolf-smartset.0 | 2021-04-30 13:05:32.547 | warn | State value to set for "wolf-smartset.0.Warmwasser.039_NULL.35001400000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.546 | warn | State value to set for "wolf-smartset.0.Warmwasser.039_NULL.35000900000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.546 | warn | State value to set for "wolf-smartset.0.Warmwasser.238_Warmwasser.35000500000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.546 | warn | State value to set for "wolf-smartset.0.Warmwasser.238_Warmwasser.35000400000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.542 | warn | State value to set for "wolf-smartset.0.Heizung.058_Direkter_Heizkreis.34001800000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.541 | warn | State value to set for "wolf-smartset.0.Heizung.058_Direkter_Heizkreis.34001700000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.541 | warn | State value to set for "wolf-smartset.0.Heizung.058_Direkter_Heizkreis.34001600000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.541 | warn | State value to set for "wolf-smartset.0.Heizung.058_Direkter_Heizkreis.34001100000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.541 | warn | State value to set for "wolf-smartset.0.Heizung.058_Direkter_Heizkreis.34000500000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.540 | warn | State value to set for "wolf-smartset.0.Heizung.058_Direkter_Heizkreis.34000100000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.540 | warn | State value to set for "wolf-smartset.0.Heizung.058_Direkter_Heizkreis.34000000000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.540 | warn | State value to set for "wolf-smartset.0.Heizung.222_Wartung.22010500000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.539 | warn | State value to set for "wolf-smartset.0.Heizung.058_Direkter_Heizkreis.22003500000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.539 | warn | State value to set for "wolf-smartset.0.Heizung.058_Direkter_Heizkreis.22003400000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.539 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18015400001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.539 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18014500001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.538 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18014300001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.538 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18014200001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.538 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18014100001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.538 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18011000001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.537 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18005100001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.537 | warn | State value to set for "wolf-smartset.0.Warmwasser.238_Warmwasser.18005000001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.537 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18003500001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.536 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18003300001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.536 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18002600001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.536 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18001600001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.536 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18001200001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.535 | warn | State value to set for "wolf-smartset.0.Warmwasser.238_Warmwasser.18001000001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.535 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18000800001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.535 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18000500001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:32.534 | warn | State value to set for "wolf-smartset.0.Heizung.058_Direkter_Heizkreis.34000400000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.442 | warn | State value to set for "wolf-smartset.0.Warmwasser.238_Warmwasser.35000400000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.414 | warn | State value to set for "wolf-smartset.0.Warmwasser.238_Warmwasser.35000500000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.413 | warn | State value to set for "wolf-smartset.0.Warmwasser.039_NULL.35001400000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.413 | warn | State value to set for "wolf-smartset.0.Warmwasser.039_NULL.35000900000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.413 | warn | State value to set for "wolf-smartset.0.Warmwasser.039_NULL.35000800000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.412 | warn | State value to set for "wolf-smartset.0.Warmwasser.238_Warmwasser.18001000001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.412 | warn | State value to set for "wolf-smartset.0.Warmwasser.238_Warmwasser.18005000001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.408 | warn | State value to set for "wolf-smartset.0.Heizung.058_Direkter_Heizkreis.34001600000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.408 | warn | State value to set for "wolf-smartset.0.Heizung.058_Direkter_Heizkreis.34000500000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.408 | warn | State value to set for "wolf-smartset.0.Heizung.058_Direkter_Heizkreis.34000400000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.407 | warn | State value to set for "wolf-smartset.0.Heizung.058_Direkter_Heizkreis.34001100000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.407 | warn | State value to set for "wolf-smartset.0.Heizung.058_Direkter_Heizkreis.34000100000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.407 | warn | State value to set for "wolf-smartset.0.Heizung.058_Direkter_Heizkreis.34000000000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.406 | warn | State value to set for "wolf-smartset.0.Heizung.058_Direkter_Heizkreis.34001700000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.406 | warn | State value to set for "wolf-smartset.0.Heizung.058_Direkter_Heizkreis.34001800000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.406 | warn | State value to set for "wolf-smartset.0.Heizung.222_Wartung.22010500000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.405 | warn | State value to set for "wolf-smartset.0.Heizung.058_Direkter_Heizkreis.22003500000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.405 | warn | State value to set for "wolf-smartset.0.Heizung.058_Direkter_Heizkreis.22003400000" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.405 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18003500001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.405 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18003300001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.404 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18000800001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.404 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18014500001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.404 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18005100001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.403 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18002600001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.403 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18011000001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.403 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18001200001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.402 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18001600001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.402 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18000500001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.402 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18015400001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.401 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18014300001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.401 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18014200001" has wrong type "string" but has to be "number"
wolf-smartset.0 | 2021-04-30 13:05:30.401 | warn | State value to set for "wolf-smartset.0.Heizung.210_Wärmeerzeuger_1.18014100001" has wrong type "string" but has to be "number"

`

**Comment by MeisterTR** [comment]
fixed
