### ISSUE TITLE
No "typ" at folder objects below wolf-smartset.0.

### ISSUE THREAD

**Issue by dp20eic** [iobroker-community-adapters/ioBroker.wolf-smartset#205]
Hello,

I have a question regarding the data structure under "Objects" and the right "Type"

Is it correct, that all folders below "Wolf-Smartset.0", are not designed as a "channel". Only the objects themselves, this makes it difficult to create an "alias" since each value must be specified individually and not the whole folder with all the objects included.

![image](https://user-images.githubusercontent.com/71387331/177531313-0bfe88d4-ed7f-426c-9e6f-ee651a2f2ba2.png)

with kind regards
Bernd

12.09.2022
also missing some units at "Übersicht"!

![image](https://user-images.githubusercontent.com/71387331/189577114-0f5dacfa-ab73-4ec2-a67a-923dedf4632a.png)

The first I did insert original are all entries are empty.

VG

**Comment by dp20eic** [comment]
Das ist schade, dann doch HomeAssistent nehmen ;)

**Comment by Apollon77** [comment]
Was ist schade? Das Du gefragt wirst ob das Issue noch existiert und gebeten wirst es zu bestätigen mit nem kurzen Post? Nichts anderes sagt dieser Post von stalebot ... So, whats the issue?

Ja es hat noch kein Entwickler Zeit gehabt sich das Issue anzusehen.

**Comment by dp20eic** [comment]
> Was ist schade? Das Du gefragt wirst ob das Issue noch existiert und gebeten wirst es zu bestätigen mit nem kurzen Post? Nichts anderes sagt dieser Post von stalebot ... So, whats the issue?
> 
> Ja es hat noch kein Entwickler Zeit gehabt sich das Issue anzusehen.

Das war mit einem Augenzwinkern, sorry falls meine Art von Humor aneckt.
Und ja, wenn das Problem behoben wäre, dann hätte ich das Problem geschlossen :)
Ja, das Problem ist noch immer vorhanden, genau wie oben beschrieben.

VG

**Comment by Apollon77** [comment]
@dp20eic Try github version. folders and last level channel should be correctly created now

**Comment by dp20eic** [comment]
Hallo @Apollon77,
gerade in meiner Testumgebung auf die Github Version 1.1.0 gewechselt. Sieht gut aus :+1: 

VG
Bernd
