### ISSUE TITLE
Question: Statistic values

### ISSUE THREAD

**Issue by dp20eic** [iobroker-community-adapters/ioBroker.wolf-smartset#213]
Hello,
I just noticed that there are these entries.

![image](https://user-images.githubusercontent.com/71387331/189521235-592e8e90-84d7-47ff-9ac6-32991389751a.png)

Can someone tell me where the values come from or whether these are just dummy entries. How can I get meaningful values, do I have to unlock something in the Wolf Cloud -> Expert level?

**Comment by Apollon77** [comment]
maybe better also ask in Forum?
