### ISSUE TITLE
no reconnect after connection lost

### ISSUE THREAD

**Issue by MeisterTR** [iobroker-community-adapters/ioBroker.wolf-smartset#214]
SESSION UPDATE ERROR: Request failed with status code 401

**Comment by e-i-k-e** [comment]
I would be very grateful if this problem could be fixed.

**Comment by e-i-k-e** [comment]
> COuld be fixed on Github version

Many Thanks. The adapter then works.

I get the following errors.
![image](https://user-images.githubusercontent.com/83473829/213807114-34d97506-1c74-4307-bf1c-2cac7786a8fd.png)

**Comment by Apollon77** [comment]
Then check your DNS please!! EAI_AGAIN with a domainname means that DNS lookup of that domainname is not possible!!

ETIMEOUT means that there is a network timeout ...

**Comment by e-i-k-e** [comment]
@Apollon77 
Thanks. Now I just have to think about how I can localize the error. (Pfsense as DNS Server + PIHole).

Back to topic again.

I get the following error very often. Rebooting the adapter fixes the problem immediately.

![image](https://user-images.githubusercontent.com/83473829/214683166-29d435b5-dcf9-471e-9449-54d71e0c8458.png)

**Comment by Apollon77** [comment]
Pklease use the current GitHub version and check also #241
