### ISSUE TITLE
API GET GUI DESK. ERROR: Error: Request failed with status code 400

### ISSUE THREAD

**Issue by Manuel1607** [iobroker-community-adapters/ioBroker.wolf-smartset#215]
Hallo ich nutze Wolf smartes in folgender Kombination 
Version 1.0.0 in C:/ioBroker/node_modules/iobroker.wolf-smartset, node: v18.9.0, js-controller: 4.0.23

leider bekomme ich seit heute immer die oben beschriebene Fehlermeldung. Hat jemand hier eine Lösung für?

**Comment by Apollon77** [comment]
Funktioniert denn die seite vom gert noch wenn du sie normal im Browser aufrufst?

**Comment by Manuel1607** [comment]
Welche meinst du ? die smartes Seite von Wolf? Ja die funktioniert ganz normal

**Comment by dp20eic** [comment]
Hi,
Das sind die bei mir in den letzten 7 Tagen im Log aufgetauchten Meldungen.
Zu der Zeit ging sowohl die APP auf Android als auch der Zugang über den Browser.

[error_Wolf-Smartset_Adapter.zip](https://github.com/iobroker-community-adapters/ioBroker.wolf-smartset/files/9896298/error_Wolf-Smartset_Adapter.zip)

**Comment by muhlatte** [comment]
Servus Kollegen,

könntet ihr das Problem mit der Fehlermeldung lösen? Wenn ja was ist die Lösung?
Zudem kommt bei mir ständig die Warnmeldung
´´´
<html>
<body>


TypeError: Cannot read properties of undefined (reading 'Values')
--



</body>
</html>
Bei mir kommt die auch ständig obwohl ich Zugang über die Wolf-Smartset Seite habe.

´´

Ich benutze die 1.0.0 Version aus dem beta Repo und habe ein Link Home in meiner CGB-2-14.

Dank euch und Gruß
Daniel

**Comment by Apollon77** [comment]
Please check github version

**Comment by muhlatte** [comment]
Leider mit Github Version immernoch dasselbe Problem:
![image](https://user-images.githubusercontent.com/104367123/213909649-75419562-337f-4bce-807c-7effb13d61bf.png)

Instanz ist connected und Anlage über Smartset Homepage erreichbar.

**Comment by Apollon77** [comment]
Bitte aktuellste GitHub version versuchen

**Comment by muhlatte** [comment]
Problem ist leider immernoch unverändert, auch mit der GitHub Version von heute morgen. Tritt nicht sofort bei Instanz Start auf, aber wenn der Fehler Mal da ist geht er über einen Adapterneustart auch nicht weg (Adapter startet nicht hoch weil er sich mit dem Gerät nicht verbinden kann).

Wenn du Mehrinfos brauchst kann ich sie dir gerne zur Verfügung stellen

VG Daniel

**Comment by Apollon77** [comment]
Ok, ich habe nochmal kleinigkeiten optimiert und das geht als 1.1.1 jetzt ins Beta/Latest

**Comment by muhlatte** [comment]
Hallo Apollon77,

das 429er Problem habe ich nicht mehr, jedoch habe ich aktuell ab und an den Code 500. Für was steht der? Wie oft kann man beim Homelink aktualisieren?

Dank dir und Gruß
Daniel

**Comment by Apollon77** [comment]
Ohne log - am besten debug log - kann ich dazu nichts sagen.

Ich denke das minimum polling interval sind 15s aktuell, ab wann es Probleme gibt keine Ahnung
