### ISSUE TITLE
direkte Datenverbindung statt Portal ?

### ISSUE THREAD

**Issue by geigl** [iobroker-community-adapters/ioBroker.wolf-smartset#249]
kein Bug des Adapters

Problem:
Der Portalserver von Wolf ist extrem oft nicht erreichbar. Wäre es möglich in den Adapter eine Direktverbindung zum ISM7 einzubauen um die Daten zu sammeln? Die Wolf-App kann diese lokale Verbindung.

Besten Dank

**Comment by Apollon77** [comment]
WIe ist das Protokoll? Wie geht das? Geht der Wolf Adapter da nicht mit?

**Comment by geigl** [comment]
Ich habe heute eigentlich nur durch Zufall die lokale Funktion der Wolf-App entdeckt. Keine Ahnung welches Protokoll dahinter liegt, ich vermute es müsste ident sein mit der Portalverbindung. Der Wolf-Adapter hat keine Einstellmöglichkeit für die lokale IP.

**Comment by geigl** [comment]
Ich habe eine Anfrage bei Wolf gestellt bezüglich der Abfrage und des Protokolls.

**Comment by geigl** [comment]
Leider gibt Wolf keine Auskunft über das Protokoll.
ABER: Das Problem mit dem Portalserver liegt lt. Wolf daran, dass sekündlich Anmeldungen vom Adapter erfolgen aber keine Abmeldungen. Der Server interpretiert dies als Angriff und sperrt den Account.
Könntest du bitte eine Einstellmöglichkeit der Abfragen/Minute in den Adapter einbauen!

**Comment by Apollon77** [comment]
Also der Adapter macht schon seit der Version 1.0 keine sekündlichen neuen Anmeldungen mehr sondern merkt und reused die session so langewie es geht - also bis der Server sagt das Sie nicht mehr gültig ist. Bitte Updaten

**Comment by Apollon77** [comment]
Also GitHub hat 1.1.1 ...........

**Comment by geigl** [comment]
die habe ich verwendet

**Comment by geigl** [comment]
läuft jetzt ohne Probleme

**Comment by kopierschnitte** [comment]
> WIe ist das Protokoll? Wie geht das? Geht der Wolf Adapter da nicht mit?

Siehe hier: https://github.com/zivillian/ism7mqtt

Wäre toll, wenn der Adapter dies auch oder anstelle machen würde. Gäbe ja dann für Cloud keinen Grund mehr...

**Comment by mcm1957** [comment]
> > WIe ist das Protokoll? Wie geht das? Geht der Wolf Adapter da nicht mit?
> 
> Siehe hier: https://github.com/zivillian/ism7mqtt
> 
> Wäre toll, wenn der Adapter dies auch oder anstelle machen würde. Gäbe ja dann für Cloud keinen Grund mehr...

This issue os closed for more than a year. If you want to report a new bug or siggest a new featute please open a new issue.
