### ISSUE TITLE
Zwei Instanzen

### ISSUE THREAD

**Issue by wartungsmonteur** [iobroker-community-adapters/ioBroker.wolf-smartset#259]
Hallo

Vielen Dank für dieses super Addon. Ich weiß nicht ob das hier die richtige Stelle für meine Frage ist.

Ich möchte gern wissen ob man auch zwei oder drei ism7 Module damit in den Home-Assistenten integrieren kann. Ich habe selber drei Geräte damit laufen. Zwei davon als Hybridinstallation, eine Therme und eine Wärmepumpe. Sollte dies noch nicht möglich sein,  aber eventuell technisch machbar, würde ich diese Erweiterung auch gern als Sponsor unterstützen.
Vielen Dank.

**Comment by Apollon77** [comment]
Ich verstehe die frage nicht ganz? Ja du kannst mehrere Instanzen vom Adapter anlegen und ggf anderen cloud accounts nutzen oder was ist genau gemeint (Bedenke: Ich persönlich habe weniger als Null Ahnung von Wolf systemen!) Vllt ist die Frage auch im Forum besser aufgehoben?

**Comment by wartungsmonteur** [comment]
HalloIch möchte einfach nur die Entitäten von zwei weiteren ism7 Modulen in den Home-Assistenten integrieren und möchte dann diese mit Hilfe von Helfern verknüpfen.Beispiel:Eine Entität aus ism7 von Therme schaltet eine Entität aus der Wärmepumpe.Grüße Michael 
-------- Ursprüngliche Nachricht --------Von: Ingo Fischer ***@***.***> Datum: 21.04.23  23:23  (GMT+01:00) An: "iobroker-community-adapters/ioBroker.wolf-smartset" ***@***.***> Cc: wartungsmonteur ***@***.***>, Author ***@***.***> Betreff: Re: [iobroker-community-adapters/ioBroker.wolf-smartset] Zwei
  Instanzen (Issue #259) 
Ich verstehe die frage nicht ganz? Ja du kannst mehrere Instanzen vom Adapter anlegen und ggf anderen cloud accounts nutzen oder was ist genau gemeint (Bedenke: Ich persönlich habe weniger als Null Ahnung von Wolf systemen!) Vllt ist die Frage auch im Forum besser aufgehoben?

**Comment by wartungsmonteur** [comment]
Hallo
Ja das meinte ich auch, lege ich den zweiten Adapter genauso an wie den ersten Adapter ?
Dazu einfach das Addon mit den Daten des zweiten Adapters konfigurieren ? 
Vielen Dank für die Hilfe.

**Comment by Apollon77** [comment]
Einfach unter "Adapter" auf plus drücken dann gibts eine zweite Instanz mit .1 am ende ... das dann unter Instanzen konfigurieren

**Comment by wartungsmonteur** [comment]
Bitte entschuldige, aber ich verstehe das nicht ganz. Wo finde ich diesen Adapter mit dem + ?
Im Home-Assistenten ? Du kannst mir auch gern direkt mailen unter info@wartungsmonteur.de
Gern würde ich auch was sponsern für deine Hilfe. Ich kenne mich halt nicht so aus mit dieser Plattform hier.

**Comment by dp20eic** [comment]
> Bitte entschuldige, aber ich verstehe das nicht ganz. Wo finde ich diesen Adapter mit dem + ?
> Im Home-Assistenten ? Du kannst mir auch gern direkt mailen unter [info@wartungsmonteur.de](mailto:info@wartungsmonteur.de)
> Gern würde ich auch was sponsern für deine Hilfe. Ich kenne mich halt nicht so aus mit dieser Plattform hier.

Moin,

das ist ein Adapter für `ioBroker` nicht für `home-assistant` ich denke `home-assistant` hat da seinen eigenen Adapter, soweit ich mich da erinnere [Home-Assistant](https://www.home-assistant.io/integrations/wolflink/)

VG
Bernd

**Comment by dp20eic** [comment]
> Hallo
> Ja das meinte ich auch, lege ich den zweiten Adapter genauso an wie den ersten Adapter ?
> Dazu einfach das Addon mit den Daten des zweiten Adapters konfigurieren ?
> Vielen Dank für die Hilfe.

Moin,
beim ISAM7 Adapter meldest Du die Anlage ja im Portal von Wolf an, danach hast Du sicherlich mehrere Anlagen im Menü 
![grafik](https://user-images.githubusercontent.com/71387331/233863183-ea49fd73-1e1b-4732-a58b-1c6e8e2f2d66.png)

Da der `ioBroker` Adapter ja nur die Information aus dem Web-Portal von Wolf zieht, sollten dann auch alle Anlagen abgefragt werden, soweit die Theorie.

@Apollon77 ist meine Annahme korrekt?

VG
Bernd

**Comment by wartungsmonteur** [comment]
Hallo
Jso ist es bei mir. Es werden drei ism7 angezeigt, jede mit einer separaten IP.

Eine Anlage habe ich im HA dann eingefügt. Funktioniert auch super, im Mqtt sind 237 Entitäten und vier Geräte.

Um nun die anderen zwei ism7 hinzufügen zu können binde ich die genauso ein wie den ersten Adapter oder überschreibe ich dann die Daten des zuerst hinzug

**Comment by dp20eic** [comment]
> Eine Anlage habe ich im HA dann eingefügt.

Moin,
nochmal, dieser Adapter ist für **`ioBroker`** wie Du das in **`HA`** machen musst, das musst Du dort fragen, siehe meinen anderen Post hier https://github.com/iobroker-community-adapters/ioBroker.wolf-smartset/issues/259#issuecomment-1519145247

VG
Bernd

**Comment by wartungsmonteur** [comment]
Hallo
Dieser Adapter ist für HA und Iobroker. Im Iobroker kanna man halt mehrere Instanzen mühelos erstellen. Trotzdem vielen Dank für die schnelle Antwort.
Viele Grüße und eine schöne Woche.

**Comment by wartungsmonteur** [comment]
![Screenshot_20230424_113109_Chrome](https://user-images.githubusercontent.com/131309361/233957794-c27c0d7b-9bff-4b35-8dcc-f94307c9cd3b.jpg)
Das läuft bei mir im Home-Assistent. Vielleicht gibt es auch zwei unterschiedliche Versionen.

**Comment by dp20eic** [comment]
> ![Screenshot_20230424_113109_Chrome](https://user-images.githubusercontent.com/131309361/233957794-c27c0d7b-9bff-4b35-8dcc-f94307c9cd3b.jpg) Das läuft bei mir im Home-Assistent. Vielleicht gibt es auch zwei unterschiedliche Versionen.

Moin,

und wo steht da bitte schön `iobroker.wolf-smartset`?
Da ist ein Adapter von **b3nn0**  und nennt sich **Ism7MQTT**!

Dann noch etwas, `ioBroker` ist nicht `Home-Assistant`, `ioBroker` ist geschrieben in `node.js` und Konfiguration in `json`, wohingegen `Home-Assistant` in `python` und `yaml` geschrieben ist, somit sind die von Natur aus nicht wirklich kompatibel!

Wenn Du mal bei `Github` suchst, dann findest Du auch das richtige https://github.com/b3nn0/hassio-addon-ism7mqtt, ich denke, da bist Du dann richtig, hier auf jeden Fall nicht!

Denn, wenn Du das hier liest https://github.com/iobroker-community-adapters/ioBroker.wolf-smartset dann steht da nichts von `home-assistant`

Ich habe mir das in `home-assistant` angeschaut und das ist nicht dieser Adapter.

VG
Bernd
