### ISSUE TITLE
Please configure user, password and device in config

### ISSUE THREAD

**Issue by Muegic** [iobroker-community-adapters/ioBroker.wolf-smartset#260]
Hi, ich bringe die Github Version 1.1.1 bei mir nicht zum laufen und weiß nicht mehr was ich noch probieren soll.
Instanz und Adapter mehrfach neu installiert, händisch entfernt, ioBroker geupdated und gefixt.

Benutzer und Passwort habe ich korrekt eingetragen. 
Ein Klick auf Get Devices bringt für eine halbe Sekunde das Drehrad, aber ich kann meine Anlage nicht auswählen.

<html><body>

wolf-smartset.0 | 2023-04-23 22:43:52.780 | error | TypeError:  Cannot read properties of null (reading 'Id')    at  WolfSmartset.onReady  (/opt/iobroker/node_modules/iobroker.wolf-smartset/main.js:40:23)    at  WolfSmartset.emit (node:events:513:28)    at WolfSmartset.emit  (node:domain:489:12)    at  /opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.js:9139:26
-- | -- | -- | --
wolf-smartset.0 | 2023-04-23 22:43:52.698 | error | Please configure user, password and device in config
wolf-smartset.0 | 2023-04-23 22:43:52.682 | info | starting.  Version 1.1.1 (non-npm:  iobroker-community-adapters/ioBroker.wolf-smartset) in  /opt/iobroker/node_modules/iobroker.wolf-smartset, node: v16.20.0,  js-controller: 4.0.24

</body>
</html>

Danke schon mal
Markus

**Comment by Apollon77** [comment]
Warum Github version 1.1.1? Bitte die offizielle Version aus dem Beta Repo nutzen. Das wäre das erste.

Am Ende ist bei dir Konfiguration irgendwie komisch. Bitte instzanz löschen und neu anlegen

**Comment by Muegic** [comment]
Erst mal Danke für die Rückmeldung. Beiße mir aber weiterhin die Zähne an dieser Sache aus.
Habe jetzt zum Test mal ioBroker in einem neuen Container frisch aufgesetzt.
Repo auf beta umgestellt:
![grafik](https://user-images.githubusercontent.com/66391615/234671789-80beccc5-e1a3-4651-869a-bc3624845e05.png)

Unter Adapter, Expertenmodus an, auf die Katze und unter "von Github" den wolf-smarset Adapter ausgewählt und installiert
![grafik](https://user-images.githubusercontent.com/66391615/234672105-375da806-2e64-4ba6-acd7-b9e107d9e3c6.png)

Danach wird mit Adapterversion 1.1.1 angezeigt und ich habe eine Instanz angelegt
![grafik](https://user-images.githubusercontent.com/66391615/234673026-caa03f1b-4f6a-403f-bb4e-8241ecd8eeda.png)

Installation läuft ohne Fehler durch
![grafik](https://user-images.githubusercontent.com/66391615/234672508-e1ec4244-cb9c-477d-8bb2-7a62d8ffd796.png)

Die Instanz startet automatisch und ich komme direkt auf die Einstellungs-Seite.
Dort gebe ich Benutzer und Passwort an und klicke auf "get devices"
Dann kommt die Meldung dass ich die Instanz erst aktivieren soll, obwohl die bereits läuft.
Wenn ich die Seite schließe und es wieder versuche, kommt dann nur noch ganz kurz der Wartekreisel.
Also exakt das gleiche (Fehl-)verhalten wie in meiner Produktivumgebung.
![grafik](https://user-images.githubusercontent.com/66391615/234673916-96e17c2f-64e8-44f4-8e15-eb3d35e2a49a.png)

Mache ich bei der Installation schon etwas falsch?

**Comment by Muegic** [comment]
Anbei die Config von meinem Produktivsystem und der Test-Iobroker Installation.
Sind aber beide so gut wie identisch.

[Basis Config (Produktiv).txt](https://github.com/iobroker-community-adapters/ioBroker.wolf-smartset/files/11346016/Basis.Config.Produktiv.txt)
[Basis Config (Test).txt](https://github.com/iobroker-community-adapters/ioBroker.wolf-smartset/files/11346076/Basis.Config.Test.txt)

Ist zwar unwahrscheinlich, aber ich wollts mal erwähnt haben...
Ich habe dir im Januar meine Zugangsdaten zum Testen zur Verfügung gestellt (Passwort habe ich nicht geändert).
Kann es irgendwie daran liegen?
Scheinbar bin ich ja der einzige mit diesem Problem.

LG und Danke für deinen Support

**Comment by Apollon77** [comment]
Hmn ... also die Zeile

>     "devices": null,

ist falsch. entferne die mal bitte - oder entferne nochmal die instanz bitte und füge sie neu hinzu. und am besten dann direkt ein log mit dazu

**Comment by Muegic** [comment]
Habe "devices":null entfernt und Instanz neu gestartet - leider keine Änderung

Wenn ich die Instanz neu installiere und ohne user/pwd einzugeben das Fenster schließe, steht "devices":null noch nicht in der config  
[config ohne user pwd.txt](https://github.com/iobroker-community-adapters/ioBroker.wolf-smartset/files/11348800/config.ohne.user.pwd.txt)

Wenn ich Benutzer und Passwort eingebe und speicher&schließe (ohne Klick auf Get Devices) erscheint "devices":null in der config
[config mit user pwd.txt](https://github.com/iobroker-community-adapters/ioBroker.wolf-smartset/files/11348819/config.mit.user.pwd.txt)

Hier das Logfile während der Installation (mit Admin Instanz auf Loglevel info)
[Installation (info).txt](https://github.com/iobroker-community-adapters/ioBroker.wolf-smartset/files/11348834/Installation.info.txt)

Und nochmal mit Admin auf debug
[Installation (debug).txt](https://github.com/iobroker-community-adapters/ioBroker.wolf-smartset/files/11348836/Installation.debug.txt)


Ich habe heute Abend mal einen Pi mit jungfräulichem ioBroker aus der Schublade geholt und dort den Adapter/Instanz installiert - gleiches Verhalten.
Wie kann das sein, dass auf unterschiedlicher Hardware und frischem ioBroker der Adapter bei mir nicht funktioniert?
Entweder mache ich etwas während der Installation falsch (siehe Fotostory oben)?
Oder kann es an meinem Netzwerk liegen? (pihole meckert nicht & deaktivieren ändert auch nichts)

**Comment by dp20eic** [comment]
> Wie kann das sein, dass auf unterschiedlicher Hardware und frischem ioBroker der Adapter bei mir nicht funktioniert?

Moin,
ich hab keine Lösung und es klingt ja auch ziemlich seltsam.

Kannst Du nochmal alles löschen und Dir die alte 1.0.0 installieren und da schauen, ob es mit den Zugangsdaten geht?
Anschließend nur ein Update machen von 1.0.0 → 1.1.1
Dann auch noch einmal auf der Seite von Wolf, evtl. mal ein neues Passwort erstellen. 

VG
Bernd

**Comment by Muegic** [comment]
Hallelujah!!! Danke Bernd, jetzt läufts :-)

Hatte das Passwort gestern Abend noch geändert und mit der 1.1.1 gecheckt, aber machte keinen Unterschied.

Bei der Installation auf 1.0.0 kam zwar auch erst die "Please active instance" Meldung und einloggen ging nicht, aber beim zweiten Anlauf hat er dann die Zugangsdaten gefressen.
Dann das Update auf 1.1.1 und der Adapter blieb grün und jetzt läuft das Ding endlich.

Vielen lieben Dank für eure Hilfe Ingo und Bernd!
Wünsche euch ein schönes langes Wochenende!

**Comment by Apollon77** [comment]
We leave open because something IS strange as it seems

**Comment by neo-licious** [comment]
Hallo zusammen,

hatte das gleiche Problem mit der V 1.1.1 wie oben beschrieben. Der Umweg über die V 1.0.0 hat zum Erfolg geführt.

**Comment by JanS1995** [comment]
Gleiches Probem mit selbiger Lösung. Installation von 1.0.0 und dann das Update auf 1.1.1

**Comment by knowhowseeker** [comment]
Gleiches Problem mit selbiger Lösung. Musste bei 1.0.0 auch ein 2-3 Mal probieren, hat dann aber geklappt. Upgrade auf 1.1.1 und dann hatte ich alle Daten. Vielen Dank.

**Comment by vedje** [comment]
Auch bei mir gleiches Problem und gleiche Lösung. Danke.

**Comment by rootvasilij** [comment]
Blöde Frage, wie installiere ich die Version 1.0.0.
Habe auf der Adapterseite Version 1.0.0 ausgewählt und installiert, die taucht bei Instanzen aber leider nicht auf.
VG

**Comment by mcm1957** [comment]
Issue seems to be poutdated.

If you still have problems installing a specific release, please open a topic at out forum (https://forum.iobroker.net). Most likely you must select the correct repository (recommended STABLE) and press "Nach updates suchen" afterwards. If the adapter is not selectable afterwards, its likely that something at you system needs to be checked / fixed. The forum is the best place to investigate this.
