### ISSUE TITLE
Changing of parameter value does not update wolf heating

### ISSUE THREAD

**Issue by gertz167** [iobroker-community-adapters/ioBroker.wolf-smartset#282]
**Describe the bug**  
When I try to change the parameter value "35001200000" (changing of program warmwater. 0=standby, 1=auto ) to "1" or "0" the change will not be sent to wolf heating. 
When I open and login to https://www.wolf-smartset.com and change the value manually then it works correctly.

I also could not see any debug value with string "SEND VALUE" in log of iobroker.

**To Reproduce**  
1. Install and create new instance of wolf-smartset adapter in iobroker
2. change log level of wolf-smartset from "info" to debug
3. Open "Objects" in iobroker and filter for value "35001200000"
4. Change the value to "1" or "0" and enable checkbox "Wert bestätigen"
5. Open log of iobroker. There there is no log entry for wolf-smartset with value "SEND-VALUE"
6. Also open webpage  https://www.wolf-smartset.com and check for changed value. The value is still the old one. Also the heating system still has the old value.

**Expected behavior**  
Changing of value will be sent to wolf-smartset and heating system is updated with new value.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 1.1.1
 - JS-Controller version: 4.0.24 
 - Node version: v18.17.1
 - Operating system: raspbian bullseye

**Additional context**

**Comment by Apollon77** [comment]
> Change the value to "1" or "0" and enable checkbox "Wert bestätigen"

Mööööööööppp WRONG! :-)

COmmands are only executed if "Wert bestätigen" is set to false!!

So might it be a using error? Please try to leave the "Wert bestätigen" at false

**Comment by gertz167** [comment]
Ahhh. thanks. that works. :-)
