### ISSUE TITLE
no updates for values of the "Fachmannebene" 

### ISSUE THREAD

**Issue by tirregbo** [iobroker-community-adapters/ioBroker.wolf-smartset#288]
Moin,
first I want to thank you for the adapter as well!
But I have the problem, that all values that are protected by the "Fachmannpasswort"  (for example Zulufttemperatur and Ablufttemperatur) are only updating when I parallel do the login into the wolf-smartset [webinterface](https://www.wolf-smartset.com) and access the "Fachmannebene" by entering the well-known four-digit code. This was also mentioned by @tomohnejerry  in #242 
I found no solution.

I use version 1.1.1 with a ISM7 in a CHA07.
An alternative way using ism7mqtt and FHEM as a broker works with all values.
Thanks and greetings

**Comment by Apollon77** [comment]
suplicate #242
