### ISSUE TITLE
Beschreibung der einzelnen Datenpunkte

### ISSUE THREAD

**Issue by Sebastian-Lorenzen** [iobroker-community-adapters/ioBroker.wolf-smartset#294]
Hallo und vielen Dank für den Adapter!

Was für mich nicht klar ist: Mir fehlen die möglichen Werte einzelner Datenpunkte.
Z. B. "wolf-smartset.0.Benutzer.Heizung.030_Gemeinsame_Einstellungen.34003200000" - woher weiß ich, was der Wert 7 bedeutet? (Also in diesem Beispiel "Kühlen", "Heizen", "Standby", etc...)?

Auch im Zusammenspiel mit der Anleitung zum iSM8i (wo die Datenpunkte ja auch definiert sind) komme ich da zu keinem logischen Ergebnis...

Versions:
 - Adapter version: 1.1.1
 - JS-Controller version: 5.0.12
 - Node version: 18.17.1
 - Operating system: DEBIAN 12

Danke Euch
Sebastian

**Comment by Klaus-Lucas** [comment]
Hallo Sebastian,
das kannst du doch selber rausbekommen, wenn du auf der Wolf-Smartseite jeden Wert einmal setzt und schaust, welche Zahl dafür im iobroker-Adapter erscheint. Ich denke, dass 
**wolf-smartset.0.Benutzer.Heizung.030_Gemeinsame_Einstellungen.34002900000** den Text (Auto) und 
**wolf-smartset.0.Benutzer.Heizung.030_Gemeinsame_Einstellungen.34003200000** den nummerischen Wert von Auto (1) zeigt

**Menü:**
![grafik](https://github.com/iobroker-community-adapters/ioBroker.wolf-smartset/assets/36620907/360def58-2fc3-4cc1-8ec0-2ea18ad4cc14)

0 = Standby
1 = Auto
2 = Permanent
3 = Sparen

**Auto(1)**
![grafik](https://github.com/iobroker-community-adapters/ioBroker.wolf-smartset/assets/36620907/2f2d3577-9c29-4d2e-8bb3-05362f301662)

**Sparen(3)**
![grafik](https://github.com/iobroker-community-adapters/ioBroker.wolf-smartset/assets/36620907/34b1bd0c-82d5-4d9f-8c0e-768a765c010c)

**Comment by Klaus-Lucas** [comment]
Hallo @Sebastian-Lorenzen,
die Mühe brauchst du dir eigentlich nicht zu machen, da im Menü der Wolf-Smartseite ja schon alles steht.
Zudem ist das Menü geräteabhängig, womit also deine Auswahlmöglichkeiten nicht denen meiner entspricht.

**Comment by Sebastian-Lorenzen** [comment]
Ok, danke Dir für den Hinweis.
