### ISSUE TITLE
 Keine Verbindung

### ISSUE THREAD

**Issue by pp222NOH** [iobroker-community-adapters/ioBroker.wolf-smartset#330]
In meinem System sind 2 Wärmepumpen mit ISM7 im gleichen Netz. Auf die beiden Wärmepumpen kann ich über die Wolf-Smart-Set zugreifen.
Im ioBroker habe ich den Wolf Smartset Adapter installiert (1.1.1). Aber ich bekomme keine Verbindung. Ich habe auch versucht über die Version 1.0.0 erst die Adpter zu installieren. Leider hat das auch nicht funktioniert. Dann habe ich einen ISM7 aus dem System genommen. Leider auch ohne Erfolg.  
Was mache ich falsch?

ioBroker, v6.13.16
Wolf Smartset 1.1.1 und 1.0.0

![grafik](https://github.com/iobroker-community-adapters/ioBroker.wolf-smartset/assets/165469298/f8f3e178-3df7-4f9e-b863-ed4ce40ff5c9)

**Comment by flingo64** [comment]
Bei mir ähnlich: versuche den Adapter seit mehreren Tage initial einzurichten: bisher ohne Erfolg, die Fehlermeldungen sind identisch

Installation : Wolf CHA-07 mit ISM7 Modul (über Ethernet im lokalen LAN) , Portal und eBus LED sind an, Wolf SmartSet app eingerichtet und funktioniert.

SystemInfo (Docker Container on Synology NAS):

    Adapter version: 1.1.1
    Plattform: docker (official image - v9.1.2)
    Betriebssystem: linux
    Architektur: x64
    Node.js: v18.20.1
    NPM: 10.5.1
    Admin: v6.13.16

Adapter Downgrade auf 1.0.0 und Upgrade haben auch nicht geholfen. Ich kann auch mit der Version 1.0.0 kein Device auswählen.

Anbei Screenshot vom Protokoll der letzten Aktion und komplettes Log.
![grafik](https://github.com/iobroker-community-adapters/ioBroker.wolf-smartset/assets/10708998/63bf966e-24f3-4800-bc4c-1ce252bf8905)


[iobroker-wolf-smartset.log](https://github.com/iobroker-community-adapters/ioBroker.wolf-smartset/files/14970430/iobroker-wolf-smartset.log)

**Comment by flingo64** [comment]
Habe eine Lösung für mich gefunden: siehe [issue#304](https://github.com/iobroker-community-adapters/ioBroker.wolf-smartset/issues/304#issuecomment-2065277523)

**Comment by mcm1957** [comment]
fixed at 2.1.1
