### ISSUE TITLE
error since today in the logs "API GET GUI DESK. ERROR: Error: Request failed with status code 500"

### ISSUE THREAD

**Issue by handy80** [iobroker-community-adapters/ioBroker.wolf-smartset#5]
getting an error/warning since today.
is that in any way known? did I do something wrong? worked all well since a couple of weeks. app on my iPhone is still working.

`
wolf-smartset.0 | 2021-07-27 22:17:27.647 | debug | (16650) SESSION UPDATE: {"Maintenance":false}
-- | -- | -- | --
wolf-smartset.0 | 2021-07-27 22:17:27.541 | debug | (16650) Updating session!
wolf-smartset.0 | 2021-07-27 22:17:21.242 | warn | (16650) TypeError: Cannot read property 'Values' of undefined
wolf-smartset.0 | 2021-07-27 22:17:21.241 | error | (16650) API GET GUI DESK. ERROR: Error: Request failed with status code 500
wolf-smartset.0 | 2021-07-27 22:17:06.116 | warn | (16650) TypeError: Cannot read property 'Values' of undefined
wolf-smartset.0 | 2021-07-27 22:17:06.115 | error | (16650) API GET GUI DESK. ERROR: Error: Request failed with status code 500
wolf-smartset.0 | 2021-07-27 22:16:50.973 | warn | (16650) TypeError: Cannot read property 'Values' of undefined
wolf-smartset.0 | 2021-07-27 22:16:50.972 | error | (16650) API GET GUI DESK. ERROR: Error: Request failed with status code 500
wolf-smartset.0 | 2021-07-27 22:16:35.830 | warn | (16650) TypeError: Cannot read property 'Values' of undefined
wolf-smartset.0 | 2021-07-27 22:16:35.829 | error | (16650) API GET GUI DESK. ERROR: Error: Request failed with status code 500
wolf-smartset.0 | 2021-07-27 22:16:27.538 | debug | (16650) SESSION UPDATE: {"Maintenance":false}
wolf-smartset.0 | 2021-07-27 22:16:27.434 | debug | (16650) Updating session!
wolf-smartset.0 | 2021-07-27 22:16:20.705 | warn | (16650) TypeError: Cannot read property 'Values' of undefined
wolf-smartset.0 | 2021-07-27 22:16:20.704 | error | (16650) API GET GUI DESK. ERROR: Error: Request failed with status code 500
wolf-smartset.0 | 2021-07-27 22:16:05.576 | warn | (16650) TypeError: Cannot read property 'Values' of undefined
wolf-smartset.0 | 2021-07-27 22:16:05.575 | error | (16650) API GET GUI DESK. ERROR: Error: Request failed with status code 500
wolf-smartset.0 | 2021-07-27 22:16:03.448 | debug | (16650) system.adapter.admin.0: logging true
wolf-smartset.0 | 2021-07-27 22:15:50.434 | warn | (16650) TypeError: Cannot read property 'Values' of undefined
wolf-smartset.0 | 2021-07-27 22:15:50.433 | error | (16650) API GET GUI DESK. ERROR: Error: Request failed with status code 500
wolf-smartset.0 | 2021-07-27 22:15:35.297 | warn | (16650) TypeError: Cannot read property 'Values' of undefined
wolf-smartset.0 | 2021-07-27 22:15:35.296 | error | (16650) API GET GUI DESK. ERROR: Error: Request failed with status code 500
wolf-smartset.0 | 2021-07-27 22:15:27.431 | debug | (16650) SESSION UPDATE: {"Maintenance":false}
wolf-smartset.0 | 2021-07-27 22:15:27.293 | debug | (16650) Updating session!
wolf-smartset.0 | 2021-07-27 22:15:20.149 | warn | (16650) TypeError: Cannot read property 'Values' of undefined

`

**Comment by dp20eic** [comment]
Hallo @handy80 ,

Du warst schneller, ich habe auch seit ein paar Tagen Probleme, mit dem Wolf Adapter. Zuvor hatte ich aber auch mit der Handy App von Wolf Probleme und der Login auch der Login auf https://www.wolf-smartset.com/ ging nicht. Die scheinen da etwas geändert zu haben, leider habe ich keine Antwort auf meine Mail von Wolf bekommen.

[iobroker_wolf-adapter_fehler.txt](https://github.com/iobroker-community-adapters/ioBroker.wolf-smartset/files/6898828/iobroker_wolf-adapter_fehler.txt)

**Comment by handy80** [comment]
Hi @dp20eic, ich bin leider auch nicht happy mit Wolf (sowohl Heizung selber, als auch die Kulanz der Firma Wolf, mit dem Software-Support hatte ich noch nichts zu tun, addiert sich aber scheinbar schön auf)
Hätte ich gewusst, dass die Firmenpolitik und der Kundensupport derartig ist, hätte ich nicht Wolf gewählt. Aber das soll hier nicht das Thema werden.
@MeisterTR Ich hoffe, dass der Fehler schnell behoben werden könnte. Wenn noch weitere Infos benötigt werden, kann ich gern was zusammenstellen.

**Comment by MeisterTR** [comment]
Ich kann den Fehler besser abfangen. Bei mir laufen Adapter app und webportal ohne Probleme. Waren wohl Wartungsarbeiten. 
Werde aber das Errorhandling die Tage noch verbessern, dass der Adapter dann nicht abstürzt

**Comment by dp20eic** [comment]
Hi @handy80,

> Hi @dp20eic, ich bin leider auch nicht happy mit Wolf (sowohl Heizung selber, als auch die Kulanz der Firma Wolf, mit dem Software-Support hatte ich noch nichts zu tun, addiert sich aber scheinbar schön auf)
> Hätte ich gewusst, dass die Firmenpolitik und der Kundensupport derartig ist, hätte ich nicht Wolf gewählt. Aber das soll hier nicht das Thema werden.

Ich bin nicht unglücklich mit meiner Heizung, musste nach ca. 25 Jahren meine alte Bud.... erneuern und die Wolf läuft ganz gut, nur in den letzten 1-2 Wochen hatte ich ab und an Probleme, das sie sich halt vom Portal ab-, angemeldet hat. Hatte auch erst mein Netzwerk in verdacht.

VG
Bernd

**Comment by handy80** [comment]
Ach so, Das Portal hat sich glaub ich bei mir nur ein mal die letzen Wochen abgemeldet.
