### ISSUE TITLE
Heizgerät.ParameterXXXX" min/max values are wrong

### ISSUE THREAD

**Issue by x-Rainer-x** [iobroker-community-adapters/ioBroker.wolf-smartset#65]
looks like the value 5 for wolf-smartset.0.Fachmann.Heizgerät.Parameter_HG.419_Einstellungen.27010400001 is wrong.
Based on the documentation from Wolf the default value is 2

{
  "type": "state",
  "common": {
    "name": "Hysterese Kühlbetrieb",
    "type": "number",
    "role": "value",
    "read": true,
    "write": true,
    "unit": "K",
    "min": 5,
    "max": 10,
    "step": 0.5
  },
  "native": {
    "ValueId": 27010400001,
    "ParameterId": 27010400001,
    "ControlType": 6
  },
  "_id": "wolf-smartset.0.Fachmann.Heizgerät.Parameter_HG.419_Einstellungen.27010400001",
  "acl": {
    "object": 1636,
    "state": 1636,
    "file": 1632,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1634017970967
}

**Comment by Apollon77** [comment]
@x-Rainer-x Is this still relevan? Min/Max values are retruíeved from wolf systems and set then here

**Comment by Apollon77** [comment]
Please try GitHub version and send debug log ... logging got enhanced

**Comment by MeisterTR** [comment]
min max values are given from the api, if its wrong, there must be a failure in the api
