### ISSUE TITLE
Restart loop bei Serverproblemen

### ISSUE THREAD

**Issue by kopierschnitte** [iobroker-community-adapters/ioBroker.wolf-smartset#74]
**Describe the bug**  
Wenn die eigene Internetverbindung "hakt" oder aber der Wolf-Server gerade nicht verfügbar ist (wie z. B. gerade eben), dann stürzt der Adapter ab und iobroker sorgt dafür, dass er manuell neugestartet werden muss.

**To Reproduce**  
Adapter bei fehlender Internetverbindung starten.

**Expected behavior**  
Adapter sollte prüfen, ob ein Login erfolgreich war bzw. die Portalseite überhaupt erreicht werden kann.
Alternativ wäre eine Fehlerbehandlung möglich, so dass der Adapter nicht mit einer "uncaught exception" abstürzt.

**Screenshots & Logfiles**  
`<html>
<body>

host.iobroker | 2021-10-19 21:46:32.795 | warn | Do not restart adapter system.adapter.wolf-smartset.0 because restart loop detected
-- | -- | -- | --
host.iobroker | 2021-10-19 21:46:32.795 | error | instance system.adapter.wolf-smartset.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.iobroker | 2021-10-19 21:46:32.795 | error | Caught by controller[1]: at WolfSmartset.main (/opt/iobroker/node_modules/iobroker.wolf-smartset/main.js:62:3)
host.iobroker | 2021-10-19 21:46:32.795 | error | Caught by controller[1]: at processTicksAndRejections (internal/process/task_queues.js:95:5)
host.iobroker | 2021-10-19 21:46:32.795 | error | Caught by controller[1]: at WolfSmartSet.init (/opt/iobroker/node_modules/iobroker.wolf-smartset/lib/wss.js:38:25)
host.iobroker | 2021-10-19 21:46:32.794 | error | Caught by controller[1]: at WolfSmartSet._createSession (/opt/iobroker/node_modules/iobroker.wolf-smartset/lib/wss.js:249:11)
host.iobroker | 2021-10-19 21:46:32.792 | error | Caught by controller[1]: TypeError: Cannot read property 'token_type' of undefined
host.iobroker | 2021-10-19 21:46:32.789 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
wolf-smartset.0 | 2021-10-19 21:46:31.846 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason

</body>
</html>`

**Versions:**  
 - Adapter version: 1.0.0
 - JS-Controller version: 3.3.18
 - Node version: 14.18.1
 - Operating system: Ubuntu

**Comment by loemic87** [comment]
Bei mir das gleiche Problem. Mal häufiger, mal weniger häufig. Einziger Unterschied bei mir in den System-Daten. Mein System läuft noch auf Node 12.22.5
