### ISSUE TITLE
Benutzer - Warmwasser

### ISSUE THREAD

**Issue by Einklaus** [iobroker-community-adapters/ioBroker.wolf-smartset#86]
Hallo,
es gibt keinen Parameter für die Warmwassertemperatur.

Benutzer Warmwasser zeigt bei der 030_Gemeinsame Einstellung jeweils 2 mal "Warmwassersolltemperatur eingestellt" und "Programmanwahl".
Bei 238_Warmwasser fehlt die aktuelle Warmwasser Temperatur

![image](https://user-images.githubusercontent.com/42099224/140604538-b321f312-4911-446a-a334-edd56cb38d45.png)

Hier die Anzeige von Wolf Smartset
![image](https://user-images.githubusercontent.com/42099224/140604884-3449ef59-ba9d-4fb3-95ea-0fd6acff06f6.png)

Grüße
Einklaus

**Comment by kese262** [comment]
Hallo,
bei mir heißt es "SF Speicherfühler" 
Zu finden unter Heizung>Übersicht und dann ist es bei mir der zweite Wert.

VG
